MenuBar.selectionArc = 10
MenuBar.selectionEmbeddedInsets = 5,1,5,1
SplitPaneDivider.style = plain
SplitPane.background = $Component.borderColor
SplitPane.dividerSize = 1

#---- FlatFileExplorer ----
Tree.background = $Panel.background
ScrollPane.border = 0,0,0,0
