#
# Copyright 2021 FormDev Software GmbH
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

#---- FlatEditorPane ----

FlatEditorPane.background = #2b2b2b
FlatEditorPane.caretColor = @foreground
FlatEditorPane.selectionBackground = #214283
FlatEditorPane.currentLineHighlight = #323232
FlatEditorPane.markOccurrencesColor = #52503A
FlatEditorPane.markAllHighlightColor = #32593D
FlatEditorPane.matchedBracketBackground = lighten(#3B514D,3%)
FlatEditorPane.matchedBracketBorderColor = $FlatEditorPane.matchedBracketBackground


#---- FlatEditorPane.style ----

FlatEditorPane.style.property = @foreground
FlatEditorPane.style.variable = @foreground
# use semitransparent background because it is painted over mark occurrences background
FlatEditorPane.style.variable.background = #00ff0018
FlatEditorPane.style.number = #6897BB
FlatEditorPane.style.color = #6897BB
# use semitransparent background because it is painted over mark occurrences background
FlatEditorPane.style.color.background = #ffffff10
FlatEditorPane.style.string = #6A8759
FlatEditorPane.style.function = #CC7832
FlatEditorPane.style.type = #8C8C8C
FlatEditorPane.style.reservedWord = #CC7832
FlatEditorPane.style.literalBoolean = #CC7832
FlatEditorPane.style.operator = #888
FlatEditorPane.style.separator = #888
FlatEditorPane.style.whitespace = @foreground
FlatEditorPane.style.comment = #808080
FlatEditorPane.style.comment.italic = true


#---- FlatEditorPane.gutter ----

FlatEditorPane.gutter.background = $FlatEditorPane.background
FlatEditorPane.gutter.borderColor = $Component.borderColor
FlatEditorPane.gutter.lineNumberColor = @disabledForeground


#---- FlatEditorPane.errorstrip ----

FlatEditorPane.errorstrip.caretMarkerColor = $FlatEditorPane.caretColor
