#
# Copyright 2021 FormDev Software GmbH
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

#---- FlatEditorPane ----

FlatEditorPane.background = #282c34
FlatEditorPane.caretColor = #bbbbbb
FlatEditorPane.selectionBackground = #404859
FlatEditorPane.currentLineHighlight = #2c313c
FlatEditorPane.markOccurrencesColor = #353940
FlatEditorPane.markAllHighlightColor = #32593D
FlatEditorPane.matchedBracketBackground = lighten(#3B514D,3%)
FlatEditorPane.matchedBracketBorderColor = $FlatEditorPane.matchedBracketBackground

#---- FlatEditorPane.style ----

FlatEditorPane.style.property = #ef596f
FlatEditorPane.style.variable = #ef596f
FlatEditorPane.style.number = #d19a66
FlatEditorPane.style.string = #89ca78
FlatEditorPane.style.function = #d55fde
FlatEditorPane.style.type = #8C8C8C
FlatEditorPane.style.reservedWord = #d55fde
FlatEditorPane.style.literalBoolean = #d55fde
FlatEditorPane.style.operator = #888
FlatEditorPane.style.separator = #888
FlatEditorPane.style.whitespace = @foreground
FlatEditorPane.style.comment = #5c6370
FlatEditorPane.style.comment.italic = false


#---- FlatEditorPane.gutter ----

FlatEditorPane.gutter.background = $FlatEditorPane.background
FlatEditorPane.gutter.borderColor = $Component.borderColor
FlatEditorPane.gutter.lineNumberColor = @disabledForeground


#---- FlatEditorPane.errorstrip ----

FlatEditorPane.errorstrip.caretMarkerColor = $FlatEditorPane.caretColor
